plugins {
    id 'com.enonic.defaults' version '2.1.6'
    id 'com.enonic.xp.app'
    id 'maven-publish'
}

dependencies {
    implementation xplibs.api.core
    implementation xplibs.api.portal
    include xplibs.content
    include xplibs.portal
    include xplibs.i18n
    include xplibs.node
    include xplibs.auth
    include xplibs.repo

    include "com.enonic.lib:lib-thymeleaf:3.0.0-SNAPSHOT"
    //include 'openxp.lib:appersist:1.0.0'
}

repositories {
   /*  maven {
        url 'https://dl.bintray.com/openxp/public'
    } */
    mavenLocal()
    mavenCentral()
    xp.enonicRepo( "dev" )
}
