= Discussion app

# A small comment app for enonic XP
This is to be combined with articles blogs or other content.
Easiest to use with a template and content types.

The application has defalt styling (css), this can be turned off in the application configuration on your site in content studio. +
If you want to style the discussion app your self take a look at the link:docs/style.adoc[Style documentation]

### Comment field
If you want to disable comments on a spesific part of your page add param *commentRemove* to your page xml. +
This wil stop the rendering of the comment fields.

### Latest part
Configuration: +
Headline: Ignored if empty, and will show at the top of the comment +
Size: How many comments should be shown in the latest part. +

### Language 
There are currently two supported languages Norwegian, and English. +
You can change the language used by setting the language on a the your site in content studio. +

## Market

The application should be on the enonic market. +
So you can browser XP applications tab and install it from the UI.

## Manual installation

If you want to install the application yourself build it with: + 

    gradlew build 

The jar file is located in `build/libs/discussion-vX.X.X.jar`. +
You can upload this in the server home folder or in the applications tab in enonic xp.



-- Created by Persijn Kwekkeboom pkw@enonic.com --
